services:
  fast_inspection_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIGS_SERVICE_HOST: ${CONFIGS_SERVICE_HOST:-fast_inspection_config_ms}
      CONFIGS_SERVICE_PORT: ${CONFIGS_SERVICE_PORT:-3001}
      INSPECTION_CONTROLLER_HOST: ${INSPECTION_CONTROLLER_HOST:-fast_inspection_inspection_controller_ms}
      INSPECTION_CONTROLLER_PORT: ${INSPECTION_CONTROLLER_PORT:-3003}
      EDIFICATIONS_CONTROLLER_HOST: ${EDIFICATIONS_CONTROLLER_HOST:-fast_inspection_edifications_controller_ms}
      EDIFICATIONS_CONTROLLER_PORT: ${EDIFICATIONS_CONTROLLER_PORT:-3004}
      USERS_AUTH_HOST: ${USERS_AUTH_HOST:-fast_inspection_users_auth_ms}
      USERS_AUTH_PORT: ${USERS_AUTH_PORT:-3002}
      HOST: ${HOST:-fast_inspection_gateway}
      PORT: ${PORT:-3000}
      SECRET_WORD: "Its become"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    
    networks:
      - fast_inspection_network
    
networks:
  fast_inspection_network:
    name: fast_inspection_network
