name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: "just-easy-guess"

      - name: Execute Deploy Script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "
            cd /home/deployer && 
            git clone https://github.com/Fast-Inspection-Org/fast-inspection-gateway || true && 
            cd fast-inspection-gateway && 
            git pull origin main && 
            docker-compose down &&
            PORT='${{ secrets.PORT }}' \
            SECRET_WORD='${{ secrets.SECRET_WORD }}' \
            CONFIGS_SERVICE_HOST='${{ secrets.CONFIGS_SERVICE_HOST }}' \
            CONFIGS_SERVICE_PORT='${{ secrets.CONFIGS_SERVICE_PORT }}' \
            INSPECTION_CONTROLLER_HOST='${{ secrets.INSPECTION_CONTROLLER_HOST }}' \
            INSPECTION_CONTROLLER_PORT='${{ secrets.INSPECTION_CONTROLLER_PORT }}' \
            EDIFICATIONS_CONTROLLER_HOST='${{ secrets.EDIFICATIONS_CONTROLLER_HOST }}' \
            EDIFICATIONS_CONTROLLER_PORT='${{ secrets.EDIFICATIONS_CONTROLLER_PORT }}' \
            USERS_AUTH_HOST='${{ secrets.USERS_AUTH_HOST }}' \
            USERS_AUTH_PORT='${{ secrets.USERS_AUTH_PORT }}' \ 
            docker-compose pull && 
            docker-compose up -d --build
          "